### ISSUE TITLE
parallel read error

### ISSUE THREAD

**Issue by rscohn2** [readthedocs/sphinx-notfound-page#111]
Parallel builds get an error:

```
(doc-venv) rscohn1@rscohn1-MOBL:sphinx-substitution-extensions$ make build-sample-parallel
rm -rf sample/build
+ rm -rf sample/build
sphinx-build -j 2 -W -b html sample/source sample/build
+ sphinx-build -j 2 -W -b html sample/source sample/build
Running Sphinx v3.2.1
making output directory... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 6 source files that are out of date
updating environment: [new config] 6 added, 0 changed, 0 removed
reading sources... [ 50%] five .. index
reading sources... [100%] one .. two

waiting for workers...

Extension error:
Handler <bound method EnvironmentCollector.merge_other of <notfound.extension.OrphanMetadataCollector object at 0x7f7daddd1080>> for\
 event 'env-merge-info' threw an exception (exception: )
Makefile:34: recipe for target 'build-sample-parallel' failed
make: *** [build-sample-parallel] Error 2
(doc-venv) rscohn1@rscohn1-MOBL:sphinx-substitution-extensions$
```

The test doc has an index and 5 files which only have titles:

```
..

  This is a test of parallel document builds. You need at least 5
  documents. See:
  https://github.com/adamtheturtle/sphinx-substitution-extensions/pull/173

.. toctree::
   :hidden:

   one
   two
   three
   four
   five
```
The problem is [here](https://github.com/readthedocs/sphinx-notfound-page/blob/master/notfound/extension.py#L178). I don't understand the issue, maybe it is a bug in sphinx.

The problem can avoided by declaring that the extension is not parallel read safe [here](https://github.com/readthedocs/sphinx-notfound-page/blob/master/notfound/extension.py#L295). Or by not calling the orphan code. I will file an issue with sphinx.

**Comment by humitos** [comment]
Thanks for reporting this. I don't have too much experience with parallel reading so I will need some time to research a little more about this.

> The problem is [here](https://github.com/readthedocs/sphinx-notfound-page/blob/master/notfound/extension.py?rgh-link-date=2020-09-30T15%3A00%3A23Z#L178). I don't understand the issue, maybe it is a bug in sphinx.

Why do you think the problem is there, in the code that adds `:orphan:` to the 404 page?

**Comment by rscohn2** [comment]
> Why do you think the problem is there
We are continuing the discussion in #112
