### ISSUE TITLE
CSS/JS loading blocked 

### ISSUE THREAD

**Issue by chrisjsewell** [readthedocs/sphinx-notfound-page#117]
Heya, I've just tried adding this extension to our site, but loading the page you get a load of:

```
The resource from “https://aiida.readthedocs.io/en/latest/_static/css/index.73d71520a4ca3b99cfee5594769eaaae.css” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).get_startedx.html
```

See e.g. https://aiida.readthedocs.io/projects/aiida-core/en/latest/intro/get_startedx.html

![image](https://user-images.githubusercontent.com/2997570/96739733-64292a00-13c0-11eb-9741-38fee312c22a.png)

is this something that I have done wrong?

**Comment by chrisjsewell** [comment]
Ah I've just noticed that out "base" URL is now https://aiida.readthedocs.io/projects/aiida-core/en/latest/; its got this extra `projects/aiida-core` part which I guess I need to add to `notfound_urls_prefix`

**Comment by chrisjsewell** [comment]
yeh that fixed it

**Comment by humitos** [comment]
Ups... I just saw this issue. Happy that you find out the solution already! :)
