### ISSUE TITLE
Setting configuration in conf.py

### ISSUE THREAD

**Issue by angelinekwan** [readthedocs/sphinx-notfound-page#195]
Is this the right way of setting the [Configuration options](https://sphinx-notfound-page.readthedocs.io/en/latest/configuration.html) in conf.py. I don't seems to get it working. As all my static assets are still pointing to default -` /en/latest/`

```
extensions = [
    'notfound.extension',
]

notfound_urls_prefix = 'None'
```

Thanks in advance.

**Comment by angelinekwan** [comment]
Found the right syntax is just
`notfound_urls_prefix = None`

**Comment by humitos** [comment]
Happy you figured it out! 👍🏼
