### ISSUE TITLE
Doesn't work with the Furo theme

### ISSUE THREAD

**Issue by stonecharioteer** [readthedocs/sphinx-notfound-page#211]
Hi, thanks for this project. I've been trying to use this with the Furo theme, but it hasn't been working. It's live [on my website right now.](https://stonecharioteer.com/doesnt-exist).

Am I doing something wrong though? My [conf is here.](https://github.com/stonecharioteer/blog/blob/master/source/conf.py).

**Comment by stsewd** [comment]
Hi, your project is single version, so you need to change this setting https://sphinx-notfound-page.readthedocs.io/en/latest/configuration.html#confval-notfound_urls_prefix to `None`.

**Comment by stonecharioteer** [comment]
Hi @stsewd Thanks for getting back to me. I changed it, and it didn't work. Is there something else I'm missing?

**Comment by stonecharioteer** [comment]
Thank you @stsewd! That worked.
