### ISSUE TITLE
CSS broken on 7.2.6

### ISSUE THREAD

**Issue by GrahamSH-LLK** [readthedocs/sphinx-notfound-page#224]
On a build with Sphinx 7.2.6, CSS is broken. The href's load as something that looks like `/en/2360/_CascadingStyleSheet('_static/css/tooltipster.custom.css', priority=500, rel='stylesheet', type='text/css')`. I can't find anything in our code that would do this. The broken build is at https://frc-docs--2360.org.readthedocs.build/en/2360/sss

**Comment by humitos** [comment]
Hi. I'm not able to understand your issue report. I didn't find that URL on the HTML from https://frc-docs--2360.org.readthedocs.build/en/2360/sss page.

Can you expand on your report, please?

**Comment by GrahamSH-LLK** [comment]
It started working again on read the docs theme 2.0.0rc2. I forgot to update this. My guess is that this is theme side, but I'm not totally sure.
