### ISSUE TITLE
Do not produce 404.xhtml in epub and htmlhelp

### ISSUE THREAD

**Issue by methane** [readthedocs/sphinx-notfound-page#230]
Python uses this extension but I don't want include it in ePub build.
Would you check `if app.builder.embedded` before generating 404 page?

**Comment by humitos** [comment]
Hi. Yeah, that makes sense. I think this page should only be generated if the builder is HTML (that means, no PDF nor ePUB or similars). Do you like to open a PR for this? 🙏🏼
