### ISSUE TITLE
Replace default lang and default version for prefix

### ISSUE THREAD

**Issue by stsewd** [readthedocs/sphinx-notfound-page#27]
I haven't read the code for the actual implementation, but feels like too specific to have `notfound_default_language` and `notfound_default_version` . Those can be replaced by `notfound_default_prefix`. And this would remove `notfound_no_urls_prefix`, because we can just set `notfound_default_prefix = ''`

Also, we are not in 1.0 yet, so we could break the api, or maybe we can just mark them as deprecated before removing them.

**Comment by humitos** [comment]
You are probably right.

Although, my original idea for these setting was to get them automatically from READTHEDOCS_VERSION environment variable and `app.language`.

I think it's a good thing to consider. Like,

1. if building under Read the Docs use `/lang/version/` unless `no_urls_prefix=True` (single version project) or `default_prefix` is set
1. if building outside Read the Docs, just use `default_prefix`

> Also, we are not in 1.0 yet, so we could break the api, or maybe we can just mark them as deprecated before removing them.

Breaking compatibility is something that I'd avoid unless extremely necessary. Marking the as deprecated and remove then in the future sounds good.
