### ISSUE TITLE
404.rst is built but not used

### ISSUE THREAD

**Issue by bytekeks** [readthedocs/sphinx-notfound-page#63]
A custom 404.rst is put next to the other pages. The 404.html is generated but not used.

A dead link displays the default 404 page from the extensions config. "Page not found - thanks for trying".

Did I miss something?

Conf.py:

```
extensions = [
    'authorship',
    'sphinx.ext.extlinks',
    'notfound.extension',
]

notfound_no_urls_prefix = True
```
Thank you :)

**Comment by humitos** [comment]
> The 404.html is generated but not used.

What does this mean?

I'm not sure to understand your problem/request. Can you elaborate?

**Comment by bytekeks** [comment]
I'm doing `sphinx-build` and the 404.html is created in the `build/` dir.

This is the project: [Uberspace/lab - 404.rst](https://github.com/Uberspace/lab/blob/master/source/404.rst)

It is deployed on netlify (but I think the hosting provider is not the problem).
Please see the [deployed 404 page](https://lab.uberspace.de/404.html).
It displays the default 404 page content from the extension.

I hope this makes the problem more clear.

**Comment by humitos** [comment]
Hi! I do see the custom page served at a non existing URL. For example, https://lab.uberspace.de/page/not/found.html

I think that you are saying that you are trying to use a custom `404.rst` file, but instead the default content is shown when accessed the page. If so, what version of the extension are you using? Please, try upgrading to the latest release and try again.

**Comment by acozine** [comment]
@bytekeks depending on where you are hosting your documentation, generating a 404 page may not be enought. You may also need to configure your webserver. For example, if you are using apache, you need an [ErrorDocument directive] (https://httpd.apache.org/docs/2.4/custom-error.html) to tell the server to return a specific page when it received a 404 error:
`ErrorDocument 404 /404.html`
See also [this tutorial] (https://www.digitalocean.com/community/tutorials/how-to-configure-apache-to-use-custom-error-pages-on-ubuntu-14-04)

**Comment by humitos** [comment]
Feel free to re-open if you consider this is still valid. Thanks!
