### ISSUE TITLE
Something with css and links from 404 page

### ISSUE THREAD

**Issue by EDI-N** [readthedocs/sphinx-notfound-page#79]
I think I done everything like in manual, but my 404 page isn't pretty and links go to nothing... can you help me?
Pages:
https://docsclone3.readthedocs.io/uk/latest/

**Comment by humitos** [comment]
Hi! You don't need to setup this option `notfound_no_urls_prefix = True`: https://github.com/EDI-N/DocsClone3/blob/master/docs/conf.py#L399

Also, you will probably need to define the default language as `uk`.

Please, try these and let me know. Thanks!

**Comment by EDI-N** [comment]
Thank you so much, your advice helped! It seemed that I had already tried it, but a correctly set language changes everything!
