### ISSUE TITLE
Prepend version but not language

### ISSUE THREAD

**Issue by rdb** [readthedocs/sphinx-notfound-page#80]
Thank you for developing this extension!

It appears, however, that I can choose to omit only the combination of default language and version, but not either one.

My sphinx setup has just a version prefix.  I currently have to set the default language to `'.'` to get a sensible result.  It would be great if I could just set it to `None` (or just specify the whole prefix myself, as in #27, perhaps by allowing it to be specified as a template string).

**Comment by humitos** [comment]
Thanks for your suggestion!

This will broadly wanted once Read the Docs implements this issue https://github.com/readthedocs/readthedocs.org/issues/6868
