### ISSUE TITLE
Update pypi with New Release

### ISSUE THREAD

**Issue by ScriptAutomate** [readthedocs/sphinx-notfound-page#92]
The last release of this plugin was:

- Version 0.4
- Date: **June 11th, 2019**
- pypi: https://pypi.org/project/sphinx-notfound-page/

Though, this plugin has received many updates over the past year. Can we get a new release in pypi, and perhaps automation in place that can push new versions to pypi?

**Comment by Daltz333** [comment]
I would also like this, as this fixes a warning in Sphinx 3.0.0
